<a href="https://colab.research.google.com/github/gauravmalaviya143/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [3]:
import torch
import numpy as np

# **LISTS**

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.97421178, 0.51419466, 0.62654583, 0.62909856],
       [0.06462907, 0.85397959, 0.7701217 , 0.08434908],
       [0.01229382, 0.81210826, 0.88578108, 0.52075266]])

In [6]:
np1.dtype

dtype('float64')

# **TENSORS**

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.0894, -1.7120, -0.4995, -0.8803],
        [ 0.2149, -0.0822,  1.7534,  1.0767],
        [-0.4806, -1.2194, -0.3195, -0.6424]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9742, 0.5142, 0.6265, 0.6291],
        [0.0646, 0.8540, 0.7701, 0.0843],
        [0.0123, 0.8121, 0.8858, 0.5208]], dtype=torch.float64)